# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_df_to_json <- function(df, unbox = FALSE) {
    .Call(`_jsonify_rcpp_df_to_json`, df, unbox)
}

rcpp_numeric_to_json <- function(nv, unbox = FALSE) {
    .Call(`_jsonify_rcpp_numeric_to_json`, nv, unbox)
}

rcpp_character_to_json <- function(sv, unbox = FALSE) {
    .Call(`_jsonify_rcpp_character_to_json`, sv, unbox)
}

rcpp_integer_to_json <- function(iv, unbox = FALSE) {
    .Call(`_jsonify_rcpp_integer_to_json`, iv, unbox)
}

rcpp_logical_to_json <- function(iv, unbox = FALSE) {
    .Call(`_jsonify_rcpp_logical_to_json`, iv, unbox)
}

rcpp_list_to_json <- function(lst, unbox = FALSE) {
    .Call(`_jsonify_rcpp_list_to_json`, lst, unbox)
}

rcpp_integer_matrix_to_json <- function(m, unbox = FALSE) {
    .Call(`_jsonify_rcpp_integer_matrix_to_json`, m, unbox)
}

rcpp_numeric_matrix_to_json <- function(m, unbox = FALSE) {
    .Call(`_jsonify_rcpp_numeric_matrix_to_json`, m, unbox)
}

rcpp_character_matrix_to_json <- function(m, unbox = FALSE) {
    .Call(`_jsonify_rcpp_character_matrix_to_json`, m, unbox)
}

rcpp_validate_json <- function(geojson) {
    .Call(`_jsonify_rcpp_validate_json`, geojson)
}

