# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_from_json <- function(json, simplifyDataFrame) {
    .Call(`_jsonify_rcpp_from_json`, json, simplifyDataFrame)
}

rcpp_get_col_headers <- function(x) {
    .Call(`_jsonify_rcpp_get_col_headers`, x)
}

rcpp_transpose_list <- function(x, names) {
    .Call(`_jsonify_rcpp_transpose_list`, x, names)
}

rcpp_null_to_na <- function(x) {
    invisible(.Call(`_jsonify_rcpp_null_to_na`, x))
}

rcpp_pretty_json <- function(json) {
    .Call(`_jsonify_rcpp_pretty_json`, json)
}

rcpp_minify_json <- function(json) {
    .Call(`_jsonify_rcpp_minify_json`, json)
}

rcpp_pretty_print <- function(json) {
    invisible(.Call(`_jsonify_rcpp_pretty_print`, json))
}

rcpp_df_to_json <- function(df, unbox = FALSE, digits = -1L) {
    .Call(`_jsonify_rcpp_df_to_json`, df, unbox, digits)
}

rcpp_numeric_to_json <- function(nv, unbox = FALSE, digits = -1L) {
    .Call(`_jsonify_rcpp_numeric_to_json`, nv, unbox, digits)
}

rcpp_character_to_json <- function(sv, unbox = FALSE) {
    .Call(`_jsonify_rcpp_character_to_json`, sv, unbox)
}

rcpp_integer_to_json <- function(iv, unbox = FALSE) {
    .Call(`_jsonify_rcpp_integer_to_json`, iv, unbox)
}

rcpp_logical_to_json <- function(iv, unbox = FALSE) {
    .Call(`_jsonify_rcpp_logical_to_json`, iv, unbox)
}

rcpp_list_to_json <- function(lst, unbox = FALSE, digits = -1L) {
    .Call(`_jsonify_rcpp_list_to_json`, lst, unbox, digits)
}

rcpp_integer_matrix_to_json <- function(m, unbox = FALSE) {
    .Call(`_jsonify_rcpp_integer_matrix_to_json`, m, unbox)
}

rcpp_numeric_matrix_to_json <- function(m, unbox = FALSE, digits = -1L) {
    .Call(`_jsonify_rcpp_numeric_matrix_to_json`, m, unbox, digits)
}

rcpp_character_matrix_to_json <- function(m, unbox = FALSE) {
    .Call(`_jsonify_rcpp_character_matrix_to_json`, m, unbox)
}

rcpp_validate_json <- function(json) {
    .Call(`_jsonify_rcpp_validate_json`, json)
}

