# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_df_to_json <- function(df, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_df_to_json`, df, auto_unbox)
}

rcpp_numeric_to_json <- function(nv, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_numeric_to_json`, nv, auto_unbox)
}

rcpp_character_to_json <- function(sv, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_character_to_json`, sv, auto_unbox)
}

rcpp_integer_to_json <- function(iv, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_integer_to_json`, iv, auto_unbox)
}

rcpp_logical_to_json <- function(iv, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_logical_to_json`, iv, auto_unbox)
}

rcpp_list_to_json <- function(lst, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_list_to_json`, lst, auto_unbox)
}

rcpp_integer_matrix_to_json <- function(m, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_integer_matrix_to_json`, m, auto_unbox)
}

rcpp_numeric_matrix_to_json <- function(m, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_numeric_matrix_to_json`, m, auto_unbox)
}

rcpp_character_matrix_to_json <- function(m, auto_unbox = FALSE) {
    .Call(`_jsonify_rcpp_character_matrix_to_json`, m, auto_unbox)
}

rcpp_validate_json <- function(geojson) {
    .Call(`_jsonify_rcpp_validate_json`, geojson)
}

